# Generated by Django 6.0.3 on 2026-05-05 00:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import unibicos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("dt_cad", models.DateTimeField(auto_now_add=True)),
                ("dt_alt", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=200, unique=True, verbose_name="Endereço de E-mail"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[unibicos.models.valida_cpf],
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[unibicos.models.valida_cnpj],
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("matricula", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "id_user_alt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_alt",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_user_cad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_cad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tb_usuario',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 'tb_categorias',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_comprador', models.AutoField(primary_key=True, serialize=False)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compradores',
                'db_table': 'tb_compradores',
                'ordering': ['id_comprador'],
            },
        ),
        migrations.CreateModel(
            name='Entregadores',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_entregador', models.AutoField(primary_key=True, serialize=False)),
                ('id_stripe', models.CharField(max_length=200, unique=True)),
                ('id_bancaria_stripe', models.CharField(max_length=120)),
                ('aberto', models.BooleanField(default=False)),
                ('saldo_disponivel', models.IntegerField(default=0)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entregadores',
                'db_table': 'tb_entregadores',
                'ordering': ['id_entregador'],
            },
        ),
        migrations.CreateModel(
            name='InstituicoesEnsino',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_instituicao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=10)),
                ('campus', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Instituições de Ensino',
                'db_table': 'tb_instituicoes_ensino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmailsInstituicao',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_email_instituicao', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_instituicao', to='unibicos.instituicoesensino')),
            ],
            options={
                'verbose_name_plural': 'Emails da Instituição',
                'db_table': 'tb_emails_ensino',
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unibicos.instituicoesensino'),
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_loja', models.AutoField(primary_key=True, serialize=False)),
                ('id_stripe', models.CharField(max_length=200, unique=True)),
                ('id_bancaria_stripe', models.CharField(max_length=120)),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('aberto', models.BooleanField(default=False)),
                ('departamento', models.CharField(blank=True, max_length=120, null=True)),
                ('localizacao', models.CharField(max_length=300)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('saldo_disponivel', models.IntegerField(default=0)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lojas',
                'db_table': 'tb_lojas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_movimentacoes', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(choices=[('ENTREGADOR', 'ENTREGADOR'), ('LOJA', 'LOJA')], default='LOJA', max_length=20)),
                ('valor', models.IntegerField(default=0)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movimentações',
                'db_table': 'tb_movimentacoes',
                'ordering': ['id_movimentacoes'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ("dt_cad", models.DateTimeField(auto_now_add=True)),
                ("dt_alt", models.DateTimeField(auto_now=True)),
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_stripe",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("taxa_entrega", models.IntegerField(default=0)),
                ("total_pedido", models.IntegerField(default=0)),
                (
                    "status_pedido",
                    models.CharField(
                        choices=[
                            ("CRIADO", "CRIADO"),
                            ("ACEITO_PELO_VENDEDOR", "ACEITO_PELO_VENDEDOR"),
                            ("EM_PREPARO", "EM_PREPARO"),
                            ("ENTREGA_ACEITA", "ENTREGA_ACEITA"),
                            ("SAIU_PARA_ENTREGA", "SAIU_PARA_ENTREGA"),
                            ("ENTREGUE", "ENTREGUE"),
                            ("CANCELADO", "CANCELADO"),
                        ],
                        default="CRIADO",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=4, unique=True)),
                (
                    "sala_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bloco_entrega",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "descricao_local",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unibicos.compradores",
                    ),
                ),
                (
                    "id_entregador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unibicos.entregadores",
                    ),
                ),
                (
                    "id_loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="unibicos.lojas"
                    ),
                ),
                (
                    "id_user_alt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_alt",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_user_cad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_cad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'tb_pedidos',
                'ordering': ['id_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('id_intent', models.CharField(max_length=200, unique=True)),
                ('status_pagamento', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'AGUARDANDO_PAGAMENTO'), ('PAGO', 'PAGO'), ('CONFIRMADO', 'CONFIRMADO'), ('CANCELADO', 'CANCELADO')], default='AGUARDANDO_PAGAMENTO', max_length=20)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unibicos.pedidos')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'tb_pagamentos',
                'ordering': ['id_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('descricao', models.CharField(max_length=600)),
                ('preco', models.IntegerField(default=0)),
                ('disponivel', models.BooleanField(default=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unibicos.categorias')),
                ('id_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='unibicos.lojas')),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'db_table': 'tb_produtos',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProdutos',
            fields=[
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('dt_alt', models.DateTimeField(auto_now=True)),
                ('id_pedido_produto', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_un', models.IntegerField(default=0)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_cad', to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unibicos.pedidos')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='unibicos.produtos')),
            ],
            options={
                'verbose_name_plural': 'Produtos de pedido',
                'db_table': 'tb_pedido_produtos',
                'ordering': ['id_pedido_produto'],
                'unique_together': {('id_pedido', 'id_produto')},
            },
        ),
    ]
