# Generated by Django 6.0.3 on 2026-04-30 20:27

import django.db.models.deletion
import unibicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unibicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[unibicos.models.valida_cnpj]),
        ),
        migrations.AlterField(
            model_name='pedidoprodutos',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='unibicos.produtos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[unibicos.models.valida_cpf]),
        ),
    ]
