# Generated by Django 6.0.3 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lojas",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
