# Generated by Django 6.0.3 on 2026-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0002_usuario_cnpj_alter_pedidoprodutos_id_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidos",
            name="token",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
