# Generated by Django 6.0.3 on 2026-05-19 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0002_lojas_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lojas",
            name="id_stripe",
        ),
        migrations.RemoveField(
            model_name="lojas",
            name="id_bancaria_stripe",
        ),
        migrations.RemoveField(
            model_name="entregadores",
            name="id_stripe",
        ),
        migrations.RemoveField(
            model_name="entregadores",
            name="id_bancaria_stripe",
        ),
        migrations.RemoveField(
            model_name="pedidos",
            name="id_stripe",
        ),
    ]
