# Generated by Django 6.0.3 on 2026-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0003_remove_external_account_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produtos",
            options={"ordering": ["nome"], "verbose_name_plural": "Produtos"},
        ),
        migrations.RenameField(
            model_name="produtos",
            old_name="nome_produto",
            new_name="nome",
        ),
        migrations.AlterField(
            model_name="pedidoprodutos",
            name="preco_un",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="taxa_entrega",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="total_pedido",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="preco",
            field=models.FloatField(default=0),
        ),
    ]
