# Generated by Django 6.0.3 on 2026-05-05 00:30

import unibicos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0005_alter_pedidos_status_pedido_alter_produtos_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cnpj",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[unibicos.models.valida_cnpj],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[unibicos.models.valida_cpf],
            ),
        ),
    ]
