# Generated by Django 6.0.3 on 2026-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0005_alter_pedidos_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="id_intent",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
