# Generated by Django 6.0.3 on 2026-05-20 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unibicos", "0006_alter_pagamento_id_intent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaquesLoja",
            fields=[
                ("dt_cad", models.DateTimeField(auto_now_add=True)),
                ("dt_alt", models.DateTimeField(auto_now=True)),
                ("id_saque", models.AutoField(primary_key=True, serialize=False)),
                ("pix", models.CharField(max_length=200)),
                ("valor", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "PENDENTE"),
                            ("PROCESSANDO", "PROCESSANDO"),
                            ("CONCLUIDO", "CONCLUIDO"),
                            ("CANCELADO", "CANCELADO"),
                            ("FALHOU", "FALHOU"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "id_loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saques",
                        to="unibicos.lojas",
                    ),
                ),
                (
                    "id_user_alt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_alt",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_user_cad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_cad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Saques da Loja",
                "db_table": "tb_saques_loja",
                "ordering": ["-dt_cad"],
            },
        ),
    ]
