from .categorias import *
from .compradores import *
from .entregadores import *
from .instituicoes_ensino import *
from .lojas import *
from .movimentacoes import *
from .pagamentos import *
from .produtos import *
from .pedidos import *
from .usuarios import *
from .carrinho import *
from .carteira import *
